sudo: false
language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5'
before_install:
  - git config --global user.email $GIT_NAME
  - git config --global user.name $GIT_EMAIL
  - ssh-keyscan -t rsa $DOKKU_HOST >> ~/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_2949609850cb_key -iv $encrypted_2949609850cb_iv -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/id_rsa
  - ssh-add .travis/id_rsa
  - npm i -g npm@^3.0.0
before_script:
  - npm run lint
script: .travis/deploy.sh
env:
  matrix:
    - CXX=g++-4.8
branches:
  only:
  - master
