sudo: false
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '5'
before_install:
- openssl aes-256-cbc -K $encrypted_2949609850cb_key -iv $encrypted_2949609850cb_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
- npm i -g npm@^3.0.0
before_script:
- npm run lint
script: npm run $COMMAND
env:
  matrix:
  - CXX=g++-4.8 COMMAND='deploy'
branches:
  only:
  - master
